// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new data API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for data API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetClassic(params *GetClassicParams, opts ...ClientOption) (*GetClassicOK, error)

	GetClassicJSON(params *GetClassicJSONParams, opts ...ClientOption) (*GetClassicJSONOK, error)

	GetCompact(params *GetCompactParams, opts ...ClientOption) (*GetCompactOK, error)

	GetCompactJSON(params *GetCompactJSONParams, opts ...ClientOption) (*GetCompactJSONOK, error)

	GetComplete(params *GetCompleteParams, opts ...ClientOption) (*GetCompleteOK, error)

	GetCompleteJSON(params *GetCompleteJSONParams, opts ...ClientOption) (*GetCompleteJSONOK, error)

	GetStatus(params *GetStatusParams, opts ...ClientOption) (*GetStatusOK, error)

	GetStatusJSON(params *GetStatusJSONParams, opts ...ClientOption) (*GetStatusJSONOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetClassic Weather forecast for a specified place
*/
func (a *Client) GetClassic(params *GetClassicParams, opts ...ClientOption) (*GetClassicOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetClassicParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetClassic",
		Method:             "GET",
		PathPattern:        "/classic",
		ProducesMediaTypes: []string{"application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetClassicReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetClassicOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetClassic: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetClassicJSON Weather forecast for a specified place
*/
func (a *Client) GetClassicJSON(params *GetClassicJSONParams, opts ...ClientOption) (*GetClassicJSONOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetClassicJSONParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetClassicJSON",
		Method:             "GET",
		PathPattern:        "/classic.json",
		ProducesMediaTypes: []string{"application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetClassicJSONReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetClassicJSONOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetClassicJSON: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCompact Weather forecast for a specified place
*/
func (a *Client) GetCompact(params *GetCompactParams, opts ...ClientOption) (*GetCompactOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCompactParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetCompact",
		Method:             "GET",
		PathPattern:        "/compact",
		ProducesMediaTypes: []string{"application/json;charset=UTF-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCompactReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCompactOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCompact: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCompactJSON Weather forecast for a specified place
*/
func (a *Client) GetCompactJSON(params *GetCompactJSONParams, opts ...ClientOption) (*GetCompactJSONOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCompactJSONParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetCompactJSON",
		Method:             "GET",
		PathPattern:        "/compact.json",
		ProducesMediaTypes: []string{"application/json;charset=UTF-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCompactJSONReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCompactJSONOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCompactJSON: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetComplete Weather forecast for a specified place
*/
func (a *Client) GetComplete(params *GetCompleteParams, opts ...ClientOption) (*GetCompleteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCompleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetComplete",
		Method:             "GET",
		PathPattern:        "/complete",
		ProducesMediaTypes: []string{"application/json;charset=UTF-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCompleteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCompleteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetComplete: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCompleteJSON Weather forecast for a specified place
*/
func (a *Client) GetCompleteJSON(params *GetCompleteJSONParams, opts ...ClientOption) (*GetCompleteJSONOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCompleteJSONParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetCompleteJSON",
		Method:             "GET",
		PathPattern:        "/complete.json",
		ProducesMediaTypes: []string{"application/json;charset=UTF-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCompleteJSONReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCompleteJSONOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCompleteJSON: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetStatus Weather forecast for a specified place
*/
func (a *Client) GetStatus(params *GetStatusParams, opts ...ClientOption) (*GetStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetStatusParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetStatus",
		Method:             "GET",
		PathPattern:        "/status",
		ProducesMediaTypes: []string{"application/json;charset=UTF-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetStatusReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetStatusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetStatus: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetStatusJSON Weather forecast for a specified place
*/
func (a *Client) GetStatusJSON(params *GetStatusJSONParams, opts ...ClientOption) (*GetStatusJSONOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetStatusJSONParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetStatusJSON",
		Method:             "GET",
		PathPattern:        "/status.json",
		ProducesMediaTypes: []string{"application/json;charset=UTF-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetStatusJSONReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetStatusJSONOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetStatusJSON: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
