// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStatusJSONParams creates a new GetStatusJSONParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStatusJSONParams() *GetStatusJSONParams {
	return &GetStatusJSONParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStatusJSONParamsWithTimeout creates a new GetStatusJSONParams object
// with the ability to set a timeout on a request.
func NewGetStatusJSONParamsWithTimeout(timeout time.Duration) *GetStatusJSONParams {
	return &GetStatusJSONParams{
		timeout: timeout,
	}
}

// NewGetStatusJSONParamsWithContext creates a new GetStatusJSONParams object
// with the ability to set a context for a request.
func NewGetStatusJSONParamsWithContext(ctx context.Context) *GetStatusJSONParams {
	return &GetStatusJSONParams{
		Context: ctx,
	}
}

// NewGetStatusJSONParamsWithHTTPClient creates a new GetStatusJSONParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetStatusJSONParamsWithHTTPClient(client *http.Client) *GetStatusJSONParams {
	return &GetStatusJSONParams{
		HTTPClient: client,
	}
}

/* GetStatusJSONParams contains all the parameters to send to the API endpoint
   for the get status JSON operation.

   Typically these are written to a http.Request.
*/
type GetStatusJSONParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get status JSON params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStatusJSONParams) WithDefaults() *GetStatusJSONParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get status JSON params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStatusJSONParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get status JSON params
func (o *GetStatusJSONParams) WithTimeout(timeout time.Duration) *GetStatusJSONParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get status JSON params
func (o *GetStatusJSONParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get status JSON params
func (o *GetStatusJSONParams) WithContext(ctx context.Context) *GetStatusJSONParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get status JSON params
func (o *GetStatusJSONParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get status JSON params
func (o *GetStatusJSONParams) WithHTTPClient(client *http.Client) *GetStatusJSONParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get status JSON params
func (o *GetStatusJSONParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetStatusJSONParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
