// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ojarva/api-met-no-go-client/models"
)

// GetCompleteJSONReader is a Reader for the GetCompleteJSON structure.
type GetCompleteJSONReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCompleteJSONReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCompleteJSONOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCompleteJSONOK creates a GetCompleteJSONOK with default headers values
func NewGetCompleteJSONOK() *GetCompleteJSONOK {
	return &GetCompleteJSONOK{}
}

/* GetCompleteJSONOK describes a response with status code 200, with default header values.

Success
*/
type GetCompleteJSONOK struct {
	Payload *models.METJSONForecast
}

func (o *GetCompleteJSONOK) Error() string {
	return fmt.Sprintf("[GET /complete.json][%d] getCompleteJsonOK  %+v", 200, o.Payload)
}
func (o *GetCompleteJSONOK) GetPayload() *models.METJSONForecast {
	return o.Payload
}

func (o *GetCompleteJSONOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.METJSONForecast)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
