// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ForecastSummary Summary of weather conditions.
//
// swagger:model ForecastSummary
type ForecastSummary struct {

	// symbol code
	// Required: true
	SymbolCode WeatherSymbol `json:"symbol_code"`
}

// Validate validates this forecast summary
func (m *ForecastSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSymbolCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ForecastSummary) validateSymbolCode(formats strfmt.Registry) error {

	if m.SymbolCode == nil {
		return errors.Required("symbol_code", "body", nil)
	}

	return nil
}

// ContextValidate validates this forecast summary based on context it is used
func (m *ForecastSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ForecastSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ForecastSummary) UnmarshalBinary(b []byte) error {
	var res ForecastSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
