// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// METJSONForecast GeoJSON Forecast Timeseries
//
// swagger:model METJSONForecast
type METJSONForecast struct {

	// geometry
	// Required: true
	Geometry *PointGeometry `json:"geometry"`

	// properties
	// Required: true
	Properties *Forecast `json:"properties"`

	// type
	// Example: Feature
	// Required: true
	// Enum: [Feature]
	Type *string `json:"type"`
}

// Validate validates this m e t JSON forecast
func (m *METJSONForecast) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGeometry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *METJSONForecast) validateGeometry(formats strfmt.Registry) error {

	if err := validate.Required("geometry", "body", m.Geometry); err != nil {
		return err
	}

	if m.Geometry != nil {
		if err := m.Geometry.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("geometry")
			}
			return err
		}
	}

	return nil
}

func (m *METJSONForecast) validateProperties(formats strfmt.Registry) error {

	if err := validate.Required("properties", "body", m.Properties); err != nil {
		return err
	}

	if m.Properties != nil {
		if err := m.Properties.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("properties")
			}
			return err
		}
	}

	return nil
}

var mETJsonForecastTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Feature"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		mETJsonForecastTypeTypePropEnum = append(mETJsonForecastTypeTypePropEnum, v)
	}
}

const (

	// METJSONForecastTypeFeature captures enum value "Feature"
	METJSONForecastTypeFeature string = "Feature"
)

// prop value enum
func (m *METJSONForecast) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, mETJsonForecastTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *METJSONForecast) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this m e t JSON forecast based on the context it is used
func (m *METJSONForecast) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGeometry(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProperties(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *METJSONForecast) contextValidateGeometry(ctx context.Context, formats strfmt.Registry) error {

	if m.Geometry != nil {
		if err := m.Geometry.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("geometry")
			}
			return err
		}
	}

	return nil
}

func (m *METJSONForecast) contextValidateProperties(ctx context.Context, formats strfmt.Registry) error {

	if m.Properties != nil {
		if err := m.Properties.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("properties")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *METJSONForecast) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *METJSONForecast) UnmarshalBinary(b []byte) error {
	var res METJSONForecast
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
