// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// WeatherSymbol A identifier that sums up the weather condition for this time period. May be used with https://api.met.no/weatherapi/weathericon/2.0/.
// Example: clearsky_day
//
// swagger:model WeatherSymbol
type WeatherSymbol interface{}
